import React from "react";

const Features = () => (
  <section id="features" className="features">
    <div className="container">
      <div className="section-header">
        <div className="section-badge">✨ Smart Features</div>
        <h2 className="section-title">Advanced AI technology designed specifically for JEE and NEET preparation</h2>
        <p className="section-subtitle">Experience the future of personalized learning with our cutting-edge AI algorithms</p>
      </div>
      <div className="features-grid">
        <div className="feature-card">
          <div className="feature-icon"><i className="fas fa-chart-line"></i></div>
          <h3>Real-time Monitoring</h3>
          <p>Real-time tracking of your learning progress with intelligent analysis of strengths, weaknesses, and improvement areas across all subjects.</p>
          <div className="feature-arrow">→</div>
        </div>
        <div className="feature-card">
          <div className="feature-icon"><i className="fas fa-brain"></i></div>
          <h3>Adaptive Tests</h3>
          <p>Dynamic test generation based on your performance level. Questions adapt in difficulty to challenge you appropriately and maximize learning.</p>
          <div className="feature-arrow">→</div>
        </div>
        <div className="feature-card">
          <div className="feature-icon"><i className="fas fa-target"></i></div>
          <h3>Weakness Analysis</h3>
          <p>AI identifies your weak topics and creates focused practice sessions. Get detailed insights into where you need to improve most.</p>
          <div className="feature-arrow">→</div>
        </div>
        <div className="feature-card">
          <div className="feature-icon"><i className="fas fa-route"></i></div>
          <h3>Custom Learning Path</h3>
          <p>Custom learning roadmaps generated by AI based on your goals, current level, and available time. Optimize your preparation strategy.</p>
          <div className="feature-arrow">→</div>
        </div>
        <div className="feature-card">
          <div className="feature-icon"><i className="fas fa-comments"></i></div>
          <h3>AI Tutor 24/7</h3>
          <p>Get instant answers to your doubts from our AI tutor. Available round the clock to help you understand concepts and solve problems.</p>
          <div className="feature-arrow">→</div>
        </div>
        <div className="feature-card">
          <div className="feature-icon"><i className="fas fa-lightbulb"></i></div>
          <h3>Smart Recommendations</h3>
          <p>AI suggests the best topics to study next, optimal revision schedules, and practice questions based on your performance patterns.</p>
          <div className="feature-arrow">→</div>
        </div>
      </div>
    </div>
  </section>
);

export default Features;
